In [171]:
#Read CVS into panda.
#sort randonly
# Dependencies
import requests
import json
import pandas as pd
import numpy as np
import os
import json

from config import bootcampApiUser
from config import bootcampApiPassword
from config import authCode
from config import courseID
from config import baseurl

In [172]:
filepath = os.path.join('data','grades.json')

In [173]:
grades = pd.read_json(filepath)
grades

             assignmentTitle grade                     studentName  submitted
0            0: Data Prework     A                       Ali Rizvi       True
1            0: Data Prework  None                 Ben Baumgardner      False
2            0: Data Prework     A                 Benjamin Snyder       True
3            0: Data Prework     A                      Chris Bock       True
4            0: Data Prework     A                       Chun Wong       True
5            0: Data Prework  None                 Crisharon Beale      False
6            0: Data Prework     A                     Debra Fenty       True
7            0: Data Prework  None                      Evan Kamis      False
8            0: Data Prework  None               Goutham Polavaram      False
9            0: Data Prework     A              Hunter Block-Beach       True
10           0: Data Prework  None  Ibrahim Oumar Mahamat Al Fatih      False
11           0: Data Prework  None                     Izet Bektic      False
12           0: Data Prework  None                    Kafui Ahedor      False
13           0: Data Prework     A                   Randy Dettmer       True
14           0: Data Prework     A                      Ryan Klueg       True
15           0: Data Prework     A                     Sean Atkins       True
16           0: Data Prework     A                   Sumeet Dhawan       True
17           0: Data Prework  None                 Suraj Thyagaraj      False
18           0: Data Prework  None                      Tina Gosha       True
19           0: Data Prework     A                   Valerie Lobas       True
20   10. SQLAlchemy Homework  None                       Ali Rizvi      False
21   10. SQLAlchemy Homework  None                 Ben Baumgardner      False
22   10. SQLAlchemy Homework  None                 Benjamin Snyder      False
23   10. SQLAlchemy Homework  None                      Chris Bock      False
24   10. SQLAlchemy Homework  None                       Chun Wong      False
25   10. SQLAlchemy Homework  None                 Crisharon Beale      False
26   10. SQLAlchemy Homework  None                     Debra Fenty      False
27   10. SQLAlchemy Homework  None                      Evan Kamis      False
28   10. SQLAlchemy Homework  None               Goutham Polavaram      False
29   10. SQLAlchemy Homework  None              Hunter Block-Beach      False
..                       ...   ...                             ...        ...
550                Project 1  None  Ibrahim Oumar Mahamat Al Fatih      False
551                Project 1  None                     Izet Bektic      False
552                Project 1  None                    Kafui Ahedor      False
553                Project 1  None                   Randy Dettmer      False
554                Project 1  None                      Ryan Klueg      False
555                Project 1  None                     Sean Atkins      False
556                Project 1  None                   Sumeet Dhawan      False
557                Project 1  None                 Suraj Thyagaraj      False
558                Project 1  None                      Tina Gosha      False
559                Project 1  None                   Valerie Lobas      False
560                Project 2  None                       Ali Rizvi      False
561                Project 2  None                 Ben Baumgardner      False
562                Project 2  None                 Benjamin Snyder      False
563                Project 2  None                      Chris Bock      False
564                Project 2  None                       Chun Wong      False
565                Project 2  None                 Crisharon Beale      False
566                Project 2  None                     Debra Fenty      False
567                Project 2  None                      Evan Kamis      False
568                Project 2  None               Goutham Polavaram      False
569                Project 2  None              Hunter Block-Beach      False
570                Project 2  None  Ibrahim Oumar Mahamat Al Fatih      False
571                Project 2  None                     Izet Bektic      False
572                Project 2  None                    Kafui Ahedor      False
573                Project 2  None                   Randy Dettmer      False
574                Project 2  None                      Ryan Klueg      False
575                Project 2  None                     Sean Atkins      False
576                Project 2  None                   Sumeet Dhawan      False
577                Project 2  None                 Suraj Thyagaraj      False
578                Project 2  None                      Tina Gosha      False
579                Project 2  None                   Valerie Lobas      False

[580 rows x 4 columns]

In [195]:
grades['tempNum'] = grades['assignmentTitle'].str.split('.',1)
grades['assignNum'] = grades['tempNum'].str[0]

del grades['tempNum']
grades

,assignmentTitle,grade,studentName,submitted,assignNum
0,0: Data Prework,A,Ali Rizvi,True,0: Data Prework
1,0: Data Prework,None,Ben Baumgardner,False,0: Data Prework
2,0: Data Prework,A,Benjamin Snyder,True,0: Data Prework
3,0: Data Prework,A,Chris Bock,True,0: Data Prework
4,0: Data Prework,A,Chun Wong,True,0: Data Prework
5,0: Data Prework,None,Crisharon Beale,False,0: Data Prework
6,0: Data Prework,A,Debra Fenty,True,0: Data Prework
7,0: Data Prework,None,Evan Kamis,False,0: Data Prework
8,0: Data Prework,None,Goutham Polavaram,False,0: Data Prework
9,0: Data Prework,A,Hunter Block-Beach,True,0: Data Prework
10,0: Data Prework,None,Ibrahim Oumar Mahamat Al Fatih,False,0: Data Prework
11,0: Data Prework,None,Izet Bektic,False,0: Data Prework
12,0: Data Prework,None,Kafui Ahedor,False,0: Data Prework
13,0: Data Prework,A,Randy Dettmer,True,0: Data Prework
14,0: Data Prework,A,Ryan Klueg,True,0: Data Prework
15,0: Data Prework,A,Sean Atkins,True,0: Data Prework
16,0: Data Prework,A,Sumeet Dhawan,True,0: Data Prework
17,0: Data Prework,None,Suraj Thyagaraj,False,0: Data Prework
18,0: Data Prework,None,Tina Gosha,True,0: Data Prework
19,0: Data Prework,A,Valerie Lobas,True,0: Data Prework
20,10. SQLAlchemy Homework,None,Ali Rizvi,False,10
21,10. SQLAlchemy Homework,None,Ben Baumgardner,False,10
22,10. SQLAlchemy Homework,None,Benjamin Snyder,False,10
23,10. SQLAlchemy Homework,None,Chris Bock,False,10
24,10. SQLAlchemy Homework,None,Chun Wong,False,10
25,10. SQLAlchemy Homework,None,Crisharon Beale,False,10
26,10. SQLAlchemy Homework,None,Debra Fenty,False,10
27,10. SQLAlchemy Homework,None,Evan Kamis,False,10
28,10. SQLAlchemy Homework,None,Goutham Polavaram,False,10
29,10. SQLAlchemy Homework,None,Hunter Block-Beach,False,10
...,...,...,...,...,...
550,Project 1,None,Ibrahim Oumar Mahamat Al Fatih,False,Project 1
551,Project 1,None,Izet Bektic,False,Project 1
552,Project 1,None,Kafui Ahedor,False,Project 1
553,Project 1,None,Randy Dettmer,False,Project 1
554,Project 1,None,Ryan Klueg,False,Project 1
555,Project 1,None,Sean Atkins,False,Project 1
556,Project 1,None,Sumeet Dhawan,False,Project 1
557,Project 1,None,Suraj Thyagaraj,False,Project 1
558,Project 1,None,Tina Gosha,False,Project 1
559,Project 1,None,Valerie Lobas,False,Project 1
560,Project 2,None,Ali Rizvi,False,Project 2
561,Project 2,None,Ben Baumgardner,False,Project 2
562,Project 2,None,Benjamin Snyder,False,Project 2
563,Project 2,None,Chris Bock,False,Project 2
564,Project 2,None,Chun Wong,False,Project 2
565,Project 2,None,Crisharon Beale,False,Project 2
566,Project 2,None,Debra Fenty,False,Project 2
567,Project 2,None,Evan Kamis,False,Project 2
568,Project 2,None,Goutham Polavaram,False,Project 2
569,Project 2,None,Hunter Block-Beach,False,Project 2
570,Project 2,None,Ibrahim Oumar Mahamat Al Fatih,False,Project 2
571,Project 2,None,Izet Bektic,False,Project 2
572,Project 2,None,Kafui Ahedor,False,Project 2
573,Project 2,None,Randy Dettmer,False,Project 2
574,Project 2,None,Ryan Klueg,False,Project 2
575,Project 2,None,Sean Atkins,False,Project 2
576,Project 2,None,Sumeet Dhawan,False,Project 2
577,Project 2,None,Suraj Thyagaraj,False,Project 2
578,Project 2,None,Tina Gosha,False,Project 2
579,Project 2,None,Valerie Lobas,False,Project 2

In [204]:
gradesIcare = grades[grades.assignNum.apply(lambda x: x.isnumeric())]
gradesIcare['assignNum'] = pd.to_numeric(gradesIcare['assignNum'])


gradesIcare = gradesIcare.loc[ ( gradesIcare['assignNum'] > 0 ) & (gradesIcare['assignNum'] < 4 ) ]
gradesIcare = gradesIcare.loc[ gradesIcare['studentName'] != 'Ben Baumgardner']
gradesIcare = gradesIcare.loc[gradesIcare['studentName'] != 'Crisharon Beale']
gradesIcare = gradesIcare.loc[gradesIcare['studentName'] != 'Izet Bektic']
gradesIcare = gradesIcare.loc[gradesIcare['studentName'] != 'Tina Gosha']



gradescale

In [205]:
gradesIcare

,assignmentTitle,grade,studentName,submitted,assignNum
160,1. Excel Homework,A,Ali Rizvi,True,1
162,1. Excel Homework,A+,Benjamin Snyder,True,1
163,1. Excel Homework,A,Chris Bock,True,1
164,1. Excel Homework,B+,Chun Wong,True,1
166,1. Excel Homework,B-,Debra Fenty,True,1
167,1. Excel Homework,A-,Evan Kamis,True,1
168,1. Excel Homework,A-,Goutham Polavaram,True,1
169,1. Excel Homework,A+,Hunter Block-Beach,True,1
170,1. Excel Homework,B,Ibrahim Oumar Mahamat Al Fatih,True,1
172,1. Excel Homework,B+,Kafui Ahedor,True,1
173,1. Excel Homework,A+,Randy Dettmer,True,1
174,1. Excel Homework,A+,Ryan Klueg,True,1
175,1. Excel Homework,A-,Sean Atkins,True,1
176,1. Excel Homework,A,Sumeet Dhawan,True,1
177,1. Excel Homework,A-,Suraj Thyagaraj,True,1
179,1. Excel Homework,B+,Valerie Lobas,True,1
240,2. Visual Basic Homework,A,Ali Rizvi,True,2
242,2. Visual Basic Homework,A+,Benjamin Snyder,True,2
243,2. Visual Basic Homework,A+,Chris Bock,True,2
244,2. Visual Basic Homework,A,Chun Wong,True,2
246,2. Visual Basic Homework,D+,Debra Fenty,True,2
247,2. Visual Basic Homework,Incomplete,Evan Kamis,True,2
248,2. Visual Basic Homework,A,Goutham Polavaram,True,2
249,2. Visual Basic Homework,A-,Hunter Block-Beach,True,2
250,2. Visual Basic Homework,B+,Ibrahim Oumar Mahamat Al Fatih,True,2
252,2. Visual Basic Homework,A-,Kafui Ahedor,True,2
253,2. Visual Basic Homework,A+,Randy Dettmer,True,2
254,2. Visual Basic Homework,A+,Ryan Klueg,True,2
255,2. Visual Basic Homework,B,Sean Atkins,True,2
256,2. Visual Basic Homework,A,Sumeet Dhawan,True,2
257,2. Visual Basic Homework,A+,Suraj Thyagaraj,True,2
259,2. Visual Basic Homework,A+,Valerie Lobas,True,2
260,3. Python Homework,B+,Ali Rizvi,True,3
262,3. Python Homework,A,Benjamin Snyder,True,3
263,3. Python Homework,B+,Chris Bock,True,3
264,3. Python Homework,A,Chun Wong,True,3
266,3. Python Homework,D-,Debra Fenty,True,3
267,3. Python Homework,None,Evan Kamis,False,3
268,3. Python Homework,A,Goutham Polavaram,True,3
269,3. Python Homework,A-,Hunter Block-Beach,True,3
270,3. Python Homework,A,Ibrahim Oumar Mahamat Al Fatih,True,3
272,3. Python Homework,B+,Kafui Ahedor,True,3
273,3. Python Homework,A+,Randy Dettmer,True,3
274,3. Python Homework,A+,Ryan Klueg,True,3
275,3. Python Homework,None,Sean Atkins,False,3
276,3. Python Homework,A,Sumeet Dhawan,True,3
277,3. Python Homework,B+,Suraj Thyagaraj,True,3
279,3. Python Homework,A-,Valerie Lobas,True,3

In [ ]:
grades.submitted.to_string(index=False)

In [ ]:
grades_bool

In [ ]:
f = open(filepath, "r")
for x in f:
  print(x)